import type { CalendarStylesNames, DateTimePickerStylesNames } from '@mantine/dates';
export declare const Calendar: Record<CalendarStylesNames, string>;
export declare const YearPicker: {
    calendarHeaderControlIcon: string;
    calendarHeader: string;
    calendarHeaderControl: string;
    calendarHeaderLevel: string;
    decadeLevelGroup: string;
    decadeLevel: string;
    pickerControl: string;
    yearsList: string;
    yearsListCell: string;
    yearsListRow: string;
    calendar: string;
};
export declare const MonthPicker: {
    calendarHeaderControlIcon: string;
    calendarHeader: string;
    calendarHeaderControl: string;
    calendarHeaderLevel: string;
    pickerControl: string;
    yearLevelGroup: string;
    yearLevel: string;
    monthsList: string;
    monthsListCell: string;
    monthsListRow: string;
    decadeLevelGroup: string;
    decadeLevel: string;
    yearsList: string;
    yearsListCell: string;
    yearsListRow: string;
    calendar: string;
};
export declare const DatePicker: {
    calendarHeaderControlIcon: string;
    calendarHeader: string;
    calendarHeaderControl: string;
    calendarHeaderLevel: string;
    monthLevelGroup: string;
    monthLevel: string;
    monthThead: string;
    monthRow: string;
    monthTbody: string;
    monthCell: string;
    month: string;
    weekdaysRow: string;
    weekday: string;
    day: string;
    pickerControl: string;
    yearLevelGroup: string;
    yearLevel: string;
    monthsList: string;
    monthsListCell: string;
    monthsListRow: string;
    decadeLevelGroup: string;
    decadeLevel: string;
    yearsList: string;
    yearsListCell: string;
    yearsListRow: string;
    calendar: string;
};
export declare const YearPickerInput: {
    calendarHeaderControlIcon: string;
    calendarHeader: string;
    calendarHeaderControl: string;
    calendarHeaderLevel: string;
    decadeLevelGroup: string;
    decadeLevel: string;
    pickerControl: string;
    yearsList: string;
    yearsListCell: string;
    yearsListRow: string;
    calendar: string;
    icon: string;
    label: string;
    root: string;
    wrapper: string;
    input: string;
    rightSection: string;
    required: string;
    error: string;
    description: string;
};
export declare const MonthPickerInput: {
    calendarHeaderControlIcon: string;
    calendarHeader: string;
    calendarHeaderControl: string;
    calendarHeaderLevel: string;
    pickerControl: string;
    yearLevelGroup: string;
    yearLevel: string;
    monthsList: string;
    monthsListCell: string;
    monthsListRow: string;
    decadeLevelGroup: string;
    decadeLevel: string;
    yearsList: string;
    yearsListCell: string;
    yearsListRow: string;
    calendar: string;
    icon: string;
    label: string;
    root: string;
    wrapper: string;
    input: string;
    rightSection: string;
    required: string;
    error: string;
    description: string;
};
export declare const DatePickerInput: {
    calendarHeaderControlIcon: string;
    calendarHeader: string;
    calendarHeaderControl: string;
    calendarHeaderLevel: string;
    monthLevelGroup: string;
    monthLevel: string;
    monthThead: string;
    monthRow: string;
    monthTbody: string;
    monthCell: string;
    month: string;
    weekdaysRow: string;
    weekday: string;
    day: string;
    pickerControl: string;
    yearLevelGroup: string;
    yearLevel: string;
    monthsList: string;
    monthsListCell: string;
    monthsListRow: string;
    decadeLevelGroup: string;
    decadeLevel: string;
    yearsList: string;
    yearsListCell: string;
    yearsListRow: string;
    calendar: string;
    icon: string;
    label: string;
    root: string;
    wrapper: string;
    input: string;
    rightSection: string;
    required: string;
    error: string;
    description: string;
};
export declare const DateInput: {
    calendarHeaderControlIcon: string;
    calendarHeader: string;
    calendarHeaderControl: string;
    calendarHeaderLevel: string;
    monthLevelGroup: string;
    monthLevel: string;
    monthThead: string;
    monthRow: string;
    monthTbody: string;
    monthCell: string;
    month: string;
    weekdaysRow: string;
    weekday: string;
    day: string;
    pickerControl: string;
    yearLevelGroup: string;
    yearLevel: string;
    monthsList: string;
    monthsListCell: string;
    monthsListRow: string;
    decadeLevelGroup: string;
    decadeLevel: string;
    yearsList: string;
    yearsListCell: string;
    yearsListRow: string;
    calendar: string;
    icon: string;
    label: string;
    root: string;
    wrapper: string;
    input: string;
    rightSection: string;
    required: string;
    error: string;
    description: string;
};
export declare const DateTimePicker: Record<DateTimePickerStylesNames, string>;
export declare const TimeInput: Record<import("@mantine/core").TextInputStylesNames, string>;
//# sourceMappingURL=Dates.styles-api.d.ts.map